---
version: "3.7"
services:
  proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: proxy
    restart: unless-stopped
    volumes:
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - vhost:/etc/nginx/vhost.d
      - certs:/etc/nginx/certs
      - /run/docker.sock:/tmp/docker.sock:ro
    networks:
      - net
    ports:
      - 80:80
      - 443:443
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    container_name: letsencrypt
    restart: unless-stopped
    volumes:
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - vhost:/etc/nginx/vhost.d
      - certs:/etc/nginx/certs
      - /run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_PROXY_CONTAINER: proxy
      DEFAULT_EMAIL: guillaume@masclet.net
    depends_on:
      - proxy
    networks:
      - net
volumes:
  html:
  dhparam:
  vhost:
  certs:
networks:
  net:
    external: true
