---
version: "3.7"
services:
  proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: proxy
    restart: unless-stopped
    volumes:
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - vhost:/etc/nginx/vhost.d
      - certs:/etc/nginx/certs
      - /run/docker.sock:/tmp/docker.sock:ro
      - ./conf.d/client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf:ro
      - ./conf.d/server_tokens.conf:/etc/nginx/conf.d/server_tokens.conf:ro
      - ./htpasswd:/etc/nginx/htpasswd:ro
    networks:
      - net
    ports:
      - 80:80
      - 443:443
volumes:
  html:
  dhparam:
  vhost:
  certs:
networks:
  net:
    external: true
